name: tpc

channels:
  - defaults
  - conda-forge
  - plotly

dependencies:
  - python
  - jupyterlab
  - snowflake-connector-python
  - pandas
  - matplotlib
  - seaborn
  - google-cloud-bigquery
  - google-cloud-storage
  - gcsfs
  - pip

  - pip:
    - google-resumable-media
