name: gcp

channels:
  - defaults
  - conda-forge
  - plotly

dependencies:
  - python=3.6
  - numpy
  - scipy
  - lxml
  - pandas
  - statsmodels
  - xlrd
  - scikit-learn
  - xarray
  - netcdf4
  - geojson
  - matplotlib
  - seaborn
  - plotly
  - cufflinks-py
  - bokeh
  - jupyter
  - jupyterlab
  - beautifulsoup4
  - tqdm
  - theano
  - tensorflow
  - tensorflow-hub
  - keras
  - requests
  - sqlite
  - selenium
  - geckodriver
  - h5py
  - google-cloud-bigquery
  - google-cloud-bigtable
  - google-cloud-datastore
  - google-cloud-language
  - google-cloud-pubsub
  - google-cloud-storage
  - pip

  - pip:
    - google-cloud-automl
    - google-cloud-iot
    - google-cloud-speech
    - ftransc

