name: tpc

channels:
  - defaults
  - conda-forge
  - plotly

dependencies:
  - python
  - jupyterlab
  - snowflake-connector-python=2.2.6
  - pandas
  - pyarrow>=0.17
  - matplotlib
  - seaborn
  - google-cloud-bigquery
  - google-cloud-storage
  - gcsfs
  - sqlparse
  - conda-build
  - pip

  - pip:
    - google-resumable-media
